-- Generated by the Organizer Library (Sun Feb 20 18:33:59 2022)
return {
    [1]={
        ["log_name"]="ghastly tathlum", 
        ["id"]=21343, 
        ["name"]="ghastly tathlum", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="grapevine cape", 
        ["id"]=11575, 
        ["name"]="grapevine cape", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="aurist's cape +1", 
        ["id"]=27620, 
        ["name"]="aurist's cape +1", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="shneddick ring", 
        ["id"]=27590, 
        ["name"]="shneddick ring", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="inyanga ring", 
        ["id"]=26207, 
        ["name"]="inyanga ring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="perfect lucky egg", 
        ["id"]=22299, 
        ["name"]="per. lucky egg", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="orunmila's torque", 
        ["id"]=10394, 
        ["name"]="orunmila's torque", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="sanctity necklace", 
        ["id"]=26023, 
        ["name"]="sanctity necklace", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="defending ring", 
        ["id"]=13566, 
        ["name"]="defending ring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="porous rope", 
        ["id"]=28409, 
        ["name"]="porous rope", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="mimir earring", 
        ["id"]=26095, 
        ["name"]="mimir earring", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="stikini ring +1", 
        ["id"]=26184, 
        ["name"]="stikini ring +1", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="eschan stone", 
        ["id"]=28415, 
        ["name"]="eschan stone", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="malignance earring", 
        ["id"]=26088, 
        ["name"]="malignance earring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="vates cape +1", 
        ["id"]=28590, 
        ["name"]="vates cape +1", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="arciela's grace +1", 
        ["id"]=28369, 
        ["name"]="arciela's grace +1", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="fucho-no-obi", 
        ["id"]=28452, 
        ["name"]="fucho-no-obi", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="artemis's medal", 
        ["id"]=11607, 
        ["name"]="artemis's medal", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="asklepian ring", 
        ["id"]=10787, 
        ["name"]="asklepian ring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="vor earring", 
        ["id"]=26096, 
        ["name"]="vor earring", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="siegel sash", 
        ["id"]=15960, 
        ["name"]="siegel sash", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="toro cape", 
        ["id"]=28615, 
        ["name"]="toro cape", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="olympus sash", 
        ["id"]=10821, 
        ["name"]="olympus sash", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="impatiens", 
        ["id"]=19761, 
        ["name"]="impatiens", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="twilight torque", 
        ["id"]=11625, 
        ["name"]="twilight torque", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="infused earring", 
        ["id"]=28475, 
        ["name"]="infused earring", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="warder's charm +1", 
        ["id"]=27505, 
        ["name"]="warder's charm +1", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="fi follet cape", 
        ["id"]=27609, 
        ["name"]="fi follet cape", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="esper stone +1", 
        ["id"]=21361, 
        ["name"]="esper stone +1", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="plumose sachet", 
        ["id"]=21358, 
        ["name"]="plumose sachet", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="paguroidea ring", 
        ["id"]=10753, 
        ["name"]="paguroidea ring", 
        ["count"]=1
    }, 
    [33]={
        ["log_name"]="lycopodium sash", 
        ["id"]=15928, 
        ["name"]="lycopodium sash", 
        ["count"]=1
    }, 
    [34]={
        ["log_name"]="witful belt", 
        ["id"]=10826, 
        ["name"]="witful belt", 
        ["count"]=1
    }, 
    [35]={
        ["log_name"]="swith cape", 
        ["id"]=11000, 
        ["name"]="swith cape", 
        ["count"]=1
    }, 
    [36]={
        ["log_name"]="moonshade earring", 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["count"]=1
    }, 
    [37]={
        ["log_name"]="embla sash", 
        ["id"]=26354, 
        ["name"]="embla sash", 
        ["count"]=1
    }, 
    [38]={
        ["log_name"]="campestres's cape", 
        ["count"]=1, 
        ["id"]=26260, 
        ["name"]="campestres's cape", 
        ["augments"]={
            [1]="Pet: M.Acc.+20 Pet: M.Dmg.+20", 
            [2]="Mag. Acc+20 /Mag. Dmg.+20", 
            [3]="Pet: Magic Damage+10", 
            [4]="Haste+10", 
            [5]="Phys. dmg. taken-10%"
        }
    }, 
    [39]={
        ["log_name"]="colossus's torque", 
        ["id"]=11590, 
        ["name"]="colossus's torque", 
        ["count"]=1
    }, 
    [40]={
        ["log_name"]="gelatinous ring +1", 
        ["id"]=10769, 
        ["name"]="gelatinous ring +1", 
        ["count"]=1
    }, 
    [41]={
        ["log_name"]="ethereal earring", 
        ["id"]=15965, 
        ["name"]="ethereal earring", 
        ["count"]=1
    }, 
    [42]={
        ["log_name"]="earthcry earring", 
        ["id"]=11037, 
        ["name"]="earthcry earring", 
        ["count"]=1
    }, 
    [43]={
        ["log_name"]="hecate's earring", 
        ["id"]=11698, 
        ["name"]="hecate's earring", 
        ["count"]=1
    }, 
    [44]={
        ["log_name"]="bishop's sash", 
        ["id"]=10820, 
        ["name"]="bishop's sash", 
        ["count"]=1
    }, 
    [45]={
        ["log_name"]="naji's loop", 
        ["id"]=26219, 
        ["name"]="naji's loop", 
        ["count"]=1
    }, 
    [46]={
        ["log_name"]="nodens gorget", 
        ["id"]=27524, 
        ["name"]="nodens gorget", 
        ["count"]=1
    }, 
    [47]={
        ["log_name"]="carrier's sash", 
        ["id"]=10832, 
        ["name"]="carrier's sash", 
        ["count"]=1
    }, 
    [48]={
        ["log_name"]="saevus pendant +1", 
        ["id"]=28364, 
        ["name"]="saevus pendant +1", 
        ["count"]=1
    }, 
    [49]={
        ["log_name"]="staunch tathlum", 
        ["id"]=22278, 
        ["name"]="staunch tathlum", 
        ["count"]=1
    }, 
    [50]={
        ["log_name"]="halasz earring", 
        ["id"]=27535, 
        ["name"]="halasz earring", 
        ["count"]=1
    }, 
    [51]={
        ["log_name"]="sirona's ring", 
        ["id"]=11646, 
        ["name"]="sirona's ring", 
        ["count"]=1
    }, 
    [52]={
        ["log_name"]="lebeche ring", 
        ["id"]=28538, 
        ["name"]="lebeche ring", 
        ["count"]=1
    }, 
    [53]={
        ["log_name"]="mendicant's earring", 
        ["id"]=28474, 
        ["name"]="mendi. earring", 
        ["count"]=1
    }, 
    [54]={
        ["log_name"]="ogapepo cape", 
        ["id"]=28644, 
        ["name"]="ogapepo cape", 
        ["count"]=1
    }, 
    [55]={
        ["log_name"]="gishdubar sash", 
        ["id"]=26323, 
        ["name"]="gishdubar sash", 
        ["count"]=1
    }, 
    [56]={
        ["log_name"]="prolix ring", 
        ["id"]=10752, 
        ["name"]="prolix ring", 
        ["count"]=1
    }, 
    [57]={
        ["log_name"]="purity ring", 
        ["id"]=27554, 
        ["name"]="purity ring", 
        ["count"]=1
    }
}