-- Generated by the Organizer Library (Sun Feb 20 18:33:59 2022)
return {
    [1]={
        ["log_name"]="eletta grip", 
        ["id"]=22216, 
        ["name"]="eletta grip", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="regal pumps +1", 
        ["id"]=28274, 
        ["name"]="regal pumps +1", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="inyanga shalwar +2", 
        ["id"]=25882, 
        ["name"]="inyanga shalwar +2", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="telchine gloves", 
        ["id"]=27048, 
        ["name"]="telchine gloves", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="grioavolr", 
        ["count"]=1, 
        ["id"]=22054, 
        ["name"]="grioavolr", 
        ["augments"]={
            [1]="\"Fast Cast\"+7", 
            [2]="INT+9", 
            [3]="Mag. Acc.+21", 
            [4]="Magic Damage +3"
        }
    }, 
    [6]={
        ["log_name"]="grioavolr", 
        ["count"]=1, 
        ["id"]=22054, 
        ["name"]="grioavolr", 
        ["augments"]={
            [1]="Blood Pact Dmg.+9", 
            [2]="Pet: INT+15", 
            [3]="Pet: Mag. Acc.+17", 
            [4]="Pet: \"Mag.Atk.Bns.\"+26"
        }
    }, 
    [7]={
        ["log_name"]="asteria mitts", 
        ["id"]=27106, 
        ["name"]="asteria mitts", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="iridal staff", 
        ["id"]=18632, 
        ["name"]="iridal staff", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="clerisy strap", 
        ["id"]=22200, 
        ["name"]="clerisy strap", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="oneiros grip", 
        ["id"]=18811, 
        ["name"]="oneiros grip", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="telchine chasuble", 
        ["id"]=26894, 
        ["name"]="telchine chas.", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="chtonic staff", 
        ["id"]=18623, 
        ["name"]="chtonic staff", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="earth staff", 
        ["id"]=17551, 
        ["name"]="earth staff", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="telchine braconi", 
        ["id"]=27235, 
        ["name"]="telchine braconi", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="hippomenes socks +1", 
        ["id"]=27410, 
        ["name"]="hippo. socks +1", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="assiduity pants +1", 
        ["id"]=28135, 
        ["name"]="assid. pants +1", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="genbu's shield", 
        ["id"]=12296, 
        ["name"]="genbu's shield", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="oranyan", 
        ["id"]=22055, 
        ["name"]="oranyan", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="inyanga tiara +2", 
        ["id"]=25577, 
        ["name"]="inyanga tiara +2", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="vanya slops", 
        ["id"]=27288, 
        ["name"]="vanya slops", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="inyanga jubbah +2", 
        ["id"]=25793, 
        ["name"]="inyanga jubbah +2", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="inspirited boots", 
        ["id"]=27464, 
        ["name"]="inspirited boots", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="vanya hood", 
        ["count"]=1, 
        ["id"]=26797, 
        ["name"]="vanya hood", 
        ["augments"]={
            [1]="Healing magic skill +20", 
            [2]="\"Cure\" spellcasting time -7%", 
            [3]="Magic dmg. taken -3"
        }
    }, 
    [24]={
        ["log_name"]="inyanga crackows +2", 
        ["id"]=25949, 
        ["name"]="inyan. crackows +2", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="vanya clogs", 
        ["id"]=27463, 
        ["name"]="vanya clogs", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="vanya robe", 
        ["id"]=26953, 
        ["name"]="vanya robe", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="shedir seraweels", 
        ["id"]=10329, 
        ["name"]="shedir seraweels", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="daybreak", 
        ["id"]=22040, 
        ["name"]="daybreak", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="convoker's doublet +3", 
        ["id"]=23456, 
        ["name"]="con. doublet +3", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="inyanga dastanas +2", 
        ["id"]=25831, 
        ["name"]="inyan. dastanas +2", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="telchine pigaches", 
        ["id"]=27405, 
        ["name"]="telchine pigaches", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="telchine cap", 
        ["id"]=26736, 
        ["name"]="telchine cap", 
        ["count"]=1
    }
}