-- Generated by the Organizer Library (Sun Feb 20 18:33:59 2022)
return {
    [1]={
        ["log_name"]="mecistopins mantle", 
        ["id"]=27596, 
        ["name"]="mecisto. mantle", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="elan strap +1", 
        ["id"]=22211, 
        ["name"]="elan strap +1", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="sacrifice torque", 
        ["id"]=15528, 
        ["name"]="sacrifice torque", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="apogee slacks +1", 
        ["id"]=27205, 
        ["name"]="apogee slacks +1", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="gridarvor", 
        ["id"]=21174, 
        ["name"]="gridarvor", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="shulmanu collar", 
        ["id"]=26026, 
        ["name"]="shulmanu collar", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="stikini ring +1", 
        ["id"]=26184, 
        ["name"]="stikini ring +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="helios band", 
        ["id"]=26737, 
        ["name"]="helios band", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="conveyance cape", 
        ["id"]=28631, 
        ["name"]="conveyance cape", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="beckoner's pigaches", 
        ["id"]=27439, 
        ["name"]="beck. pigaches", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="sancus sachet +1", 
        ["id"]=21395, 
        ["name"]="sancus sachet +1", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="merlinic shalwar", 
        ["id"]=25843, 
        ["name"]="merlinic shalwar", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="psycloth lappas", 
        ["id"]=27287, 
        ["name"]="psycloth lappas", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="tali'ah crackows +1", 
        ["id"]=25938, 
        ["name"]="tali'ah crackows +1", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="merlinic crackows", 
        ["count"]=1, 
        ["id"]=27497, 
        ["name"]="merlinic crackows", 
        ["augments"]={
            [1]="VIT+4", 
            [2]="STR+7", 
            [3]="\"Fast Cast\"+6", 
            [4]="Accuracy+4 Attack+4", 
            [5]="Mag. Acc.+8 \"Mag.Atk.Bns.\"+8"
        }
    }, 
    [16]={
        ["log_name"]="merlinic crackows", 
        ["count"]=1, 
        ["id"]=27497, 
        ["name"]="merlinic crackows", 
        ["augments"]={
            [1]="Phys. dmg. taken -3%", 
            [2]="Pet: Mag. Acc.+15", 
            [3]="\"Treasure Hunter\"+1"
        }
    }, 
    [17]={
        ["log_name"]="merlinic crackows", 
        ["count"]=1, 
        ["id"]=27497, 
        ["name"]="merlinic crackows", 
        ["augments"]={
            [1]="Mag. Acc.+25 \"Mag.Atk.Bns.\"+25", 
            [2]="Enmity-2"
        }
    }, 
    [18]={
        ["log_name"]="tali'ah turban +1", 
        ["id"]=25591, 
        ["name"]="tali'ah turban +1", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="evoker's ring", 
        ["id"]=14625, 
        ["name"]="evoker's ring", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="apogee crown +1", 
        ["id"]=26677, 
        ["name"]="apogee crown +1", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="kyrene's earring", 
        ["id"]=26078, 
        ["name"]="kyrene's earring", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="baayami sabots", 
        ["id"]=25972, 
        ["name"]="baayami sabots", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="lugalbanda earring", 
        ["id"]=26082, 
        ["name"]="lugalbanda earring", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="apogee dalmatica +1", 
        ["id"]=26853, 
        ["name"]="apo. dalmatica +1", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="glyphic horn +1", 
        ["id"]=26653, 
        ["name"]="glyphic horn +1", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="tali'ah gages +1", 
        ["id"]=25813, 
        ["name"]="tali'ah gages +1", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="apogee pumps +1", 
        ["id"]=27381, 
        ["name"]="apogee pumps +1", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="lodurr earring", 
        ["id"]=26099, 
        ["name"]="lodurr earring", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="gelos earring", 
        ["id"]=27528, 
        ["name"]="gelos earring", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="vox grip", 
        ["id"]=19058, 
        ["name"]="vox grip", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="caller's pendant", 
        ["id"]=11619, 
        ["name"]="caller's pendant", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="summoning earring", 
        ["id"]=14777, 
        ["name"]="smn. earring", 
        ["count"]=1
    }, 
    [33]={
        ["log_name"]="enticer's pants", 
        ["id"]=27323, 
        ["name"]="enticer's pants", 
        ["count"]=1
    }, 
    [34]={
        ["log_name"]="adad amulet", 
        ["id"]=26028, 
        ["name"]="adad amulet", 
        ["count"]=1
    }, 
    [35]={
        ["log_name"]="campestres's cape", 
        ["count"]=1, 
        ["id"]=26260, 
        ["name"]="campestres's cape", 
        ["augments"]={
            [1]="Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20", 
            [2]="Eva.+20 /Mag. Eva.+20", 
            [3]="Pet: Accuracy+10 Pet: Rng. Acc.+10", 
            [4]="Pet: \"Regen\"+10", 
            [5]="Pet: Damage taken -5%"
        }
    }, 
    [36]={
        ["log_name"]="merlinic dastanas", 
        ["count"]=1, 
        ["id"]=27141, 
        ["name"]="merlinic dastanas", 
        ["augments"]={
            [1]="\"Fast Cast\"+6", 
            [2]="INT+5", 
            [3]="Mag. Acc.+3", 
            [4]="\"Mag.Atk.Bns.\"+11"
        }
    }, 
    [37]={
        ["log_name"]="merlinic dastanas", 
        ["count"]=1, 
        ["id"]=27141, 
        ["name"]="merlinic dastanas", 
        ["augments"]={
            [1]="Pet: \"Mag.Atk.Bns.\"+17", 
            [2]="Blood Pact Dmg.+10", 
            [3]="Pet: DEX+10", 
            [4]="Pet: Mag. Acc.+12"
        }
    }, 
    [38]={
        ["log_name"]="baayami slops", 
        ["id"]=25905, 
        ["name"]="baayami slops", 
        ["count"]=1
    }, 
    [39]={
        ["log_name"]="baayami hat", 
        ["id"]=25565, 
        ["name"]="baayami hat", 
        ["count"]=1
    }, 
    [40]={
        ["log_name"]="keraunos", 
        ["id"]=21169, 
        ["name"]="keraunos", 
        ["count"]=1
    }, 
    [41]={
        ["log_name"]="tali'ah manteel +1", 
        ["id"]=25765, 
        ["name"]="tali'ah manteel +1", 
        ["count"]=1
    }, 
    [42]={
        ["log_name"]="psycloth tiara", 
        ["id"]=26796, 
        ["name"]="psycloth tiara", 
        ["count"]=1
    }, 
    [43]={
        ["log_name"]="beckoner's bracers", 
        ["id"]=27080, 
        ["name"]="beckoner's bracers", 
        ["count"]=1
    }, 
    [44]={
        ["log_name"]="evans earring", 
        ["id"]=27534, 
        ["name"]="evans earring", 
        ["count"]=1
    }, 
    [45]={
        ["log_name"]="varar ring +1", 
        ["id"]=26180, 
        ["name"]="varar ring +1", 
        ["count"]=1
    }, 
    [46]={
        ["log_name"]="varar ring +1", 
        ["id"]=26180, 
        ["name"]="varar ring +1", 
        ["count"]=1
    }, 
    [47]={
        ["log_name"]="lucidity sash", 
        ["id"]=28416, 
        ["name"]="lucidity sash", 
        ["count"]=1
    }, 
    [48]={
        ["log_name"]="helios boots", 
        ["id"]=27406, 
        ["name"]="helios boots", 
        ["count"]=1
    }, 
    [49]={
        ["log_name"]="beckoner's horn +1", 
        ["id"]=26769, 
        ["name"]="beckoner's horn +1", 
        ["count"]=1
    }, 
    [50]={
        ["log_name"]="tali'ah ring", 
        ["id"]=26210, 
        ["name"]="tali'ah ring", 
        ["count"]=1
    }, 
    [51]={
        ["log_name"]="speaker's ring", 
        ["id"]=26170, 
        ["name"]="speaker's ring", 
        ["count"]=1
    }, 
    [52]={
        ["log_name"]="tali'ah seraweels +2", 
        ["id"]=25885, 
        ["name"]="tali'ah sera. +2", 
        ["count"]=1
    }, 
    [53]={
        ["log_name"]="baayami cuffs", 
        ["id"]=25992, 
        ["name"]="baayami cuffs", 
        ["count"]=1
    }, 
    [54]={
        ["log_name"]="varar ring", 
        ["id"]=26179, 
        ["name"]="varar ring", 
        ["count"]=1
    }, 
    [55]={
        ["log_name"]="varar ring", 
        ["id"]=26179, 
        ["name"]="varar ring", 
        ["count"]=1
    }, 
    [56]={
        ["log_name"]="helios gloves", 
        ["id"]=27049, 
        ["name"]="helios gloves", 
        ["count"]=1
    }, 
    [57]={
        ["log_name"]="baayami robe", 
        ["id"]=26541, 
        ["name"]="baayami robe", 
        ["count"]=1
    }, 
    [58]={
        ["log_name"]="espiritus", 
        ["id"]=21149, 
        ["name"]="espiritus", 
        ["count"]=1
    }, 
    [59]={
        ["log_name"]="klouskap sash", 
        ["id"]=26335, 
        ["name"]="klouskap sash", 
        ["count"]=1
    }
}